### PR TITLE
Added Koin for DI, Fixed code style, removed unused params

### PR DESCRIPTION
**Pull request by GeorgCantor**
Added Koin for injecting data to viewModels
fixed code style, removed unused params

### CODE REVIEW

**Comment by zedlabs** [comment]
add these changes to the beta branch as I am not familiar for Koin DI

**Comment by GeorgCantor** [comment]
> add these changes to the beta branch as I am not familiar for Koin DI

Do you want to improve your project and follow best practices? If not then I will not send requests anymore. Koin is a simple framework to understand. You're doing it wrong passing the database to parameters every time from ui

**Comment by zedlabs** [comment]
> You're doing it wrong passing the database to parameters every time from ui
can you explain how Koin solves this

**Comment by GeorgCantor** [comment]
> > You're doing it wrong passing the database to parameters every time from ui
> > can you explain how Koin solves this

https://www.raywenderlich.com/9457-dependency-injection-with-koin

**Comment by GeorgCantor** [comment]
> > > You're doing it wrong passing the database to parameters every time from ui
> > > can you explain how Koin solves this
> 
> https://www.raywenderlich.com/9457-dependency-injection-with-koin

https://stackoverflow.com/questions/21522091/what-are-the-specific-benefits-of-using-di-on-android

**Comment by zedlabs** [comment]
I use this project learn different libraries, frameworks etc. while implementing, so I don't accept code that I am already not familiar with and I was planning on implementing dagger for DI here.
You are welcome to add these changes to the beta branch.

**Pull request closed without merging**
